### ISSUE TITLE
Version issue with images when using istiooc_darwin cluster up

### ISSUE THREAD

**Issue by deewhyweb** [openshift-istio/origin#10]
When I run "./istiooc_darwin cluster up" I am seeing an issue with the istio-statsd-prom-bridge pod not starting.
I am able to resolve the issue by changing the image to 
image: 'docker.io/prom/statsd-exporter:v0.6.0'

I am also seeing an issue with no traffic being reported in Kiali.  I am able to resolve this issue by changing the Kiali image to "latest": 
image: 'kiali/kiali:latest'

##### Version
oc v3.7.14
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
Run the command: ./istiooc_darwin cluster up --istio=true --istio-kiali-username=john --istio-kiali-password=password

##### Current Result
istio-statsd-prom-bridge pod does not start
Kiali does not show traffic

##### Expected Result
istio-statsd-prom-bridge pod should start
Kiali should show traffic

**Comment by knrc** [comment]
@deewhyweb Does this happen with the latest maistra release?

https://github.com/Maistra/origin/releases

I'm going to close this issue and archive the repo since the work is now taking place on the new organisation, if you still have issues then can you please raise the issue in 

https://jira.jboss.org/projects/MAISTRA

Thanks
